run:
	python -m experimentation.algorithms_executor input_files/P.txt input_files/T.txt
k:
	python -m experimentation.find_k
exp:
	python -m experimentation.test_executer
k_vis:
	python -m experimentation.k_visualizer
new_k_vis:
	python -m experimentation.new_k_visualizer